DROP TABLE IF EXISTS toilets,musics,reservations,status,reviews;
CREATE TABLE toilets (id INT PRIMARY KEY AUTO_INCREMENT,pos_id INT, pos_lat DOUBLE, pos_lng DOUBLE, sex ENUM('F','M'));
CREATE TABLE musics (id INT PRIMARY KEY AUTO_INCREMENT, toilet_id INT,word TEXT, url TEXT,updatetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reservations (id INT PRIMARY KEY AUTO_INCREMENT,toilet_id INT,password TEXT, updatetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE status (id INT PRIMARY KEY AUTO_INCREMENT,toilet_id INT, empty ENUM ('Empty','Occupied'),updatetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reviews (id INT PRIMARY KEY AUTO_INCREMENT,pos_id INT,comment TEXT,updatetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

INSERT INTO toilets VALUES (NULL,1,35.7139069,139.7581305,'F');
INSERT INTO toilets VALUES (NULL,1,35.7139069,139.7581305,'F');
INSERT INTO toilets VALUES (NULL,1,35.7139069,139.7581305,'M');
INSERT INTO toilets VALUES (NULL,1,35.7139069,139.7581305,'M');
INSERT INTO toilets VALUES (NULL,2,35.7140518,139.7611349,'F');
INSERT INTO toilets VALUES (NULL,2,35.7140518,139.7611349,'M');

INSERT INTO status VALUES (NULL,1, 'Empty', NULL);
INSERT INTO status VALUES (NULL,2, 'Empty', NULL);
INSERT INTO status VALUES (NULL,3, 'Empty', NULL);
INSERT INTO status VALUES (NULL,4, 'Empty', NULL);
INSERT INTO status VALUES (NULL,5, 'Empty', NULL);
INSERT INTO status VALUES (NULL,6, 'Empty', NULL);
