DROP TABLE IF EXISTS toilets,musics,reservations,status;
CREATE TABLE toilets (id INT PRIMARY KEY AUTO_INCREMENT,pos_id INT, pos_lat DOUBLE, pos_lng DOUBLE);
CREATE TABLE musics (id INT PRIMARY KEY AUTO_INCREMENT, toilet_id INT,word TEXT, url TEXT,updatetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reservations (id INT PRIMARY KEY AUTO_INCREMENT,toilet_id INT,password TEXT, updatetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE status (id INT PRIMARY KEY AUTO_INCREMENT,toilet_id INT, empty ENUM ('Empty','Occupied'),updatetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

INSERT INTO toilets VALUES (NULL,0,35.7139069,139.7581305);
INSERT INTO status VALUES (NULL, '0', 'Occupied', NULL);
